### ISSUE TITLE
Mixed mode assembly error in interactive mode

### ISSUE THREAD

**Issue by juliensobrier** [sdesalas/trifleJS#41]
This error happens in interactive mode only, not when using he --render option:

>TrifleJS.exe
Unhandled Exception: System.IO.FileLoadException: Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
   at TrifleJS.Program.Interactive()
   at TrifleJS.Program.Main(String[] args) in c:\...\trifleJS\Program.cs:line 88

I'm using Visual Studio 2013, the project was converted automatically. The .Net target for the solution is 4. I couldn't figure out which assembly has been compiled for .Net 2.

**Comment by juliensobrier** [comment]
This was caused by Noesis.Javascript and Newtonsoft.Json

**Comment by sdesalas** [comment]
Hi @juliensobrier.

Thanks for the bug report and related info. I'm trying to remove dependency on local installation of VC++ 2008 runtime (see #25), so I bundled dependencies for Noesis.Javascript but in doing so might have ended up causing other issues too. 

BTW this could also be related to the platform target. I'm always targetting x86 to make sure that I can have one set of binaries and dependencies working in x64 and x86. I had a similar error to yours when combining dependencies from x64 and x86 on the same project I think.

**Comment by sdesalas** [comment]
Also, you have a wider selection of downloads for Noesis.Javascript (.Net 3.5 and 4 vs x64 and x86) if you are building TrifleJS against a specific .NET version. You can [download the DLLs in this link](http://javascriptdotnet.codeplex.com/releases/view/88504).

**Comment by sdesalas** [comment]
I'll be adding some more info on this topic to the wiki. Its bound to come up again.

**Comment by juliensobrier** [comment]
I'm not very familiar with .Net, but is there a way to get npm to pull the dependencies automatically? This is how I got the right version for the 2 libraries.
